### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by RykerCohen** [wizguin/slippers#16]
Hi. so i followed all the steps and some room are still pixilated for the 2007 media server. 
2. Will this ever form into a full CPPS ready product or should I use Houdini?

**Comment by wizguin** [comment]
1. You're probably missing some of the 2007 files, some of these aren't archived and you'll need to use party rooms/remake them in flash if you really don't like the pixelation.
2. Probably not, mainly because some important files are lost forever, mostly all of the files relating to igloos which would take a lot of work to remake. The modern versions of the game are almost 100% archived.

**Comment by RykerCohen** [comment]
I downloaded all the rooms from your download.

And dang, I really wish this could come back into full fledge thing
